#!/bin/bash

set -e

if [ "$1" != "configure" ]; then
	exit 0
fi

# Run triggers below only on updates
if [ ! -e "/usr/local/TM/data/users/admin" ]; then
	exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

if [ -z "$TM" ]; then
	export TM='/usr/local/TM'
	PATH=$PATH:/usr/local/TM/bin
	export PATH
fi

# Restart hestia-web-terminal service if enabled
if [ -f "/etc/systemd/system/TM-web-terminal.service" ]; then
	systemctl daemon-reload > /dev/null 2>&1
	if systemctl is-enabled TM-web-terminal > /dev/null 2>&1; then
		systemctl restart TM-web-terminal
	fi
fi
